AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Globals:
  Function:
    Timeout: 30

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:

  CostNotifyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: 'CostNotifyLambdaRole'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole'
      Policies:
        - PolicyName: "CostNotifyLambdaCePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ce:GetCostAndUsage"
                Resource: 
                  - "*"

  CostNotifyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Role: !GetAtt CostNotifyLambdaRole.Arn
      CodeUri: cost_notify/
      Handler: app.lambda_handler
      Runtime: python3.10
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:34
      Architectures:
      - arm64
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: '{{resolve:secretsmanager:aws-sam-cost-notify-secret:SecretString:url}}'

  CostNotifyFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CostNotifyFunction}
      RetentionInDays: 365